#!/usr/bin/env python3
"""Compile real attachment-manager callbacks against UI-only stubs in the PDF harness."""
from pathlib import Path
root = Path(__file__).resolve().parents[1]
source = (root / 'MainWindow.Attachments.cs').read_text()
# Only external launch and AppData location are seams; all callback/session logic is real.
source = source.replace('using var process = Process.Start(monitor.StartInfo);', '_ = monitor.StartInfo;')
source = source.replace('Path.Combine(AppIdentity.LocalAppDataPath, "PdfAttachments")', 'ProbeRoot')
# Include the actual leave guard too, so pending-add navigation is executed, not inferred.
orientation = (root / 'MainWindow.OrientationPdf.cs').read_text()
start = orientation.index('        private bool FinishOrientationEditing(')
brace = orientation.index('{', start)
depth = 1
end = brace + 1
while depth:
    depth += (orientation[end] == '{') - (orientation[end] == '}')
    end += 1
source = source[:source.rfind('    }')] + orientation[start:end] + '\n' + source[source.rfind('    }'):]
(root / 'tests/OrientationPdfHarness/AttachmentManagerProbe.Generated.cs').write_text(
    '// Generated by tests/generate_attachment_manager_probe.py from production callbacks.\n#nullable enable\n' + source)
print('Generated production attachment manager probe')
