// Generated by tests/generate_attachment_manager_probe.py from production callbacks.
#nullable enable
using InspectionEditor.Models;
using InspectionEditor.Services;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Windows;
using System.Windows.Threading;

namespace InspectionEditor
{
    public partial class MainWindow
    {
        private sealed record PdfSessionEntry(InspectionFile Owner, string InspectionPath, PdfEditMonitor Monitor, int PendingIndex);
        private int _nextPendingPdfIndex = -1;
        private readonly List<PdfSessionEntry> _pdfSessions = new();
        private DispatcherTimer? _pdfTimer;
        private AttachmentsWindow? _attachmentsWindow;
        private bool _pdfPolling;
        private bool _pdfSaveInProgress;
        private string PdfWorkingRoot => ProbeRoot;

        private PdfEditMonitor? FindPdfMonitor(int? index) => _pdfSessions.FirstOrDefault(e =>
            ReferenceEquals(e.Owner, _currentInspection) && e.InspectionPath == _currentFilePath &&
            !e.Monitor.IsPendingAdd && e.Monitor.AttachmentIndex == index)?.Monitor;

        private void RegisterPdfMonitor(PdfEditMonitor monitor)
        {
            _pdfSessions.Add(new PdfSessionEntry(_currentInspection!, _currentFilePath!, monitor, _nextPendingPdfIndex--));
            if (_pdfTimer == null)
            {
                _pdfTimer = new DispatcherTimer { Interval = TimeSpan.FromMilliseconds(750) };
                _pdfTimer.Tick += (_, _) => PollPdfMonitors();
            }
            _pdfTimer.Start();
        }

        private bool SavePdfMutation(InspectionFile owner, string path)
        {
            if (_readOnlyMode || _isLoadingFile || !ReferenceEquals(owner, _currentInspection) || path != _currentFilePath) return false;
            SyncCurrentItemFromUI();
            MarkUnsaved();
            // Normal guarded save, including conflict detection, recovery and Last Edit provenance.
            // Timer failures are reported as monitor status, not repeated modal report-save alerts.
            _pdfSaveInProgress = true;
            try { return TrySaveCurrentInspection(); }
            finally { _pdfSaveInProgress = false; }
        }

        private void PollPdfMonitors()
        {
            if (_pdfPolling || _pdfSaveInProgress || _savingEditorChanges || _isLoadingFile) return;
            _pdfPolling = true;
            try
            {
                bool refresh = false;
                foreach (var entry in _pdfSessions.ToArray())
                {
                    if (_readOnlyMode || !ReferenceEquals(entry.Owner, _currentInspection) || entry.InspectionPath != _currentFilePath) continue;
                    string before = entry.Monitor.Status;
                    bool captured = entry.Monitor.Poll(DateTimeOffset.UtcNow, () => SavePdfMutation(entry.Owner, entry.InspectionPath));
                    refresh |= captured || before != entry.Monitor.Status;
                }
                UpdateOrientationPdfControls();
                if (refresh) _attachmentsWindow?.RefreshRows();
            }
            catch (Exception ex) { DiagnosticLogService.Log("PDF monitor poll failed; working copies retained", ex); }
            finally { _pdfPolling = false; }
        }

        private void AttachmentsButton_Click(object sender, RoutedEventArgs e)
        {
            if (_currentInspection == null || _currentFilePath == null) return;
            if (_attachmentsWindow != null) { _attachmentsWindow.Activate(); return; }
            var owner = _currentInspection;
            string path = _currentFilePath;
            var service = new PdfAttachmentService(owner);
            bool Current() => ReferenceEquals(owner, _currentInspection) && path == _currentFilePath;
            void RequireWritable()
            {
                if (!Current() || _readOnlyMode) throw new InvalidOperationException("This inspection is read-only or no longer active.");
            }
            _attachmentsWindow = new AttachmentsWindow(_readOnlyMode,
                () => Current() ? service.Enumerate().Select(row => new AttachmentsWindow.PdfRow
                {
                    Index = row.Index, Filename = row.Filename, Size = AttachmentsWindow.ReadableSize(row.SizeBytes),
                    Status = FindPdfMonitor(row.Index)?.Status ?? row.Status
                }).Concat(_pdfSessions.Where(e => ReferenceEquals(e.Owner, owner) && e.InspectionPath == path && e.Monitor.IsPendingAdd)
                    .Select(e => new AttachmentsWindow.PdfRow { Index = e.PendingIndex,
                        Filename = e.Monitor.Filename, Size = "Pending add", Status = e.Monitor.Status }))
                    .ToList() : new List<AttachmentsWindow.PdfRow>(),
                index =>
                {
                    RequireWritable();
                    SyncCurrentItemFromUI();
                    var monitor = index < 0 ? _pdfSessions.FirstOrDefault(e => e.PendingIndex == index && ReferenceEquals(e.Owner, owner) && e.InspectionPath == path && e.Monitor.IsPendingAdd)?.Monitor : FindPdfMonitor(index);
                    if (monitor == null)
                    {
                        monitor = service.Open(index, path, PdfWorkingRoot);
                        RegisterPdfMonitor(monitor);
                    }
                    service.PrepareForOpen(monitor);
                    monitor.MarkLaunched();
                    _ = monitor.StartInfo;
                },
                (file, approve) =>
                {
                    RequireWritable();
                    var pending = service.PrepareAdd(file, approve, path, PdfWorkingRoot,
                        _pdfSessions.Where(e => ReferenceEquals(e.Owner, owner) && e.InspectionPath == path)
                            .Select(e => e.Monitor.Filename));
                    if (pending == null) return false;
                    // Register before the first attempt: a failed add has a retryable owned copy,
                    // visible status, and the same navigation/close guard as an edited attachment.
                    RegisterPdfMonitor(pending);
                    return pending.RetrySave(() => SavePdfMutation(owner, path));
                },
                indices =>
                {
                    RequireWritable();
                    if (indices.Any(i => i < 0)) throw new IOException("Pending adds must be saved using Retry Save before deletion.");
                    var active = _pdfSessions.Where(e => ReferenceEquals(e.Owner, owner) && e.InspectionPath == path).ToArray();
                    var selected = active.Where(e => e.Monitor.AttachmentIndex.HasValue && indices.Contains(e.Monitor.AttachmentIndex.Value)).ToArray();
                    if (!service.Delete(indices, () => SavePdfMutation(owner, path), active.Select(e => e.Monitor).ToArray())) return false;
                    foreach (var entry in selected)
                    {
                        _pdfSessions.Remove(entry);
                        if (ReferenceEquals(_orientationPdf, entry.Monitor)) _orientationPdf = null;
                    }
                    if (_pdfSessions.Count == 0) _pdfTimer?.Stop();
                    UpdateOrientationPdfControls();
                    return true;
                },
                () =>
                {
                    RequireWritable();
                    foreach (var entry in _pdfSessions.ToArray())
                        if (ReferenceEquals(entry.Owner, owner) && entry.InspectionPath == path)
                            entry.Monitor.RetrySave(() => SavePdfMutation(owner, path));
                    UpdateOrientationPdfControls();
                }) { Owner = this };
            try { _attachmentsWindow.ShowDialog(); }
            finally { _attachmentsWindow = null; }
        }
        private bool FinishOrientationEditing(bool leaving = true)
        {
            if (_finishingOrientationPdf || _pdfPolling) return false;
            _finishingOrientationPdf = true;
            try
            {
                PollPdfMonitors();
                foreach (var entry in _pdfSessions)
                {
                    if (!entry.Monitor.CanLeave(out string reason))
                    {
                        MessageBox.Show($"{reason}\n\nFinish/save/close the PDF in its editor, then use ATTACHMENTS > Retry Save if needed. " +
                            "RED cannot detect unsaved edits held only inside another app.\n\nWorking copy retained:\n" + entry.Monitor.WorkingPath,
                            "PDF changes still pending", MessageBoxButton.OK, MessageBoxImage.Warning);
                        return false;
                    }
                }
                if (leaving)
                {
                    // Cleanup rechecks disk and can detect a late write/lock. Remove only sessions
                    // actually cleaned so a partial cleanup can safely resume the remaining monitors.
                    foreach (var entry in _pdfSessions.ToArray())
                    {
                        entry.Monitor.Cleanup();
                        _pdfSessions.Remove(entry);
                        if (ReferenceEquals(_orientationPdf, entry.Monitor)) _orientationPdf = null;
                    }
                    _pdfTimer?.Stop();
                    _orientationPdf = null;
                    UpdateOrientationPdfControls();
                }
                return true;
            }
            catch (Exception ex)
            {
                if (_pdfSessions.Count > 0) _pdfTimer?.Start();
                DiagnosticLogService.Log("PDF completion interrupted; remaining working copies retained", ex);
                MessageBox.Show(ex.Message + "\n\nPDF monitoring remains active. Finish/save/close the editor and use ATTACHMENTS > Retry Save.\n\nRetained working copies:\n" +
                    string.Join("\n", _pdfSessions.Select(entry => entry.Monitor.WorkingPath)),
                    "PDF changes still pending", MessageBoxButton.OK, MessageBoxImage.Warning);
                return false;
            }
            finally { _finishingOrientationPdf = false; }
        }
    }
}
